### PR TITLE
ci: update super linter version (v5 -> v7)

### LINKED ISSUE #44: [FEAT]: Update to a newer version of Super-Linter
### Description

According to https://github.com/super-linter/super-linter, v7.1.0 of super-linter/super-linter is available, but https://github.com/B-AROL-O/FREISA/blob/main/.github/workflows/linter.yml is still using v5.

We would like to have someone to test the new release, and either customize it or fix the codebase in case it would discover additional problems.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by davmacario**
Closes #44 

## 📑 Description

Update Super Linter from version 5(slim) to version 7(slim).
Also formatted the `.github/workflows/linter.yml` file.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

N.A.

### CODE REVIEW

**Review by gmacario — CHANGES_REQUESTED** [review]
@davmacario thank you for your contribution. Unfortunately it looks like additional changes are needed to make the build green:

image

**Comment by davmacario** [comment]
> Unfortunately it looks like additional changes are needed to make the build green

Yep, I'm creating some config files for the linters - stuff like JSCPD uses default configuration values that are causing issues.

**Comment by davmacario** [comment]
I also realized that for how GitHub Actions are configured (triggered on push - for non-main branches - and on PR), this causes 2 actions to run at the same time when pushing to a branch for which there is a PR open.

Is this wanted?

**Comment by davmacario** [comment]
@gmacario the checks are now passed.

I chose to remove some of the linters because I deemed them "too much" for this project - let me know if you have any feedback on this.

Also, let me know about the problem with duplicate jobs.

**Comment by davmacario** [comment]
To solve the duplicate job issue, I propose something like:

```yaml
job:
    lint:
        ...
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
        ...
```

**Comment by gmacario** [comment]
> To solve the duplicate job issue, I propose something like:

LGTM. Maybe you could file the duplicate runs as a separate bug, then create another PR 😉

**Review by gmacario — APPROVED** [review]

**Comment by davmacario** [comment]
I will also improve the devcontainer setup - maybe with automatic pip package installations upon launch.

**Pull request merged**
