### PR TITLE
Update README.md after nomination

### PR DESCRIPTION
**Pull request by pitdagosti**
Proposal for closing #10

### CODE REVIEW

**Comment by gmacario** [comment]
Maybe we could also update the cover image by replacing it with something like https://twitter.com/baroloteam/status/1740735338031571052 and linking it to the Community Award submission form instead?

**Comment by pitdagosti** [comment]
You mean, creating a new QR code?

**Comment by gmacario** [comment]
> You mean, creating a new QR code?

No, just the link from the image to the form, something like

```text
[![2023-12-29-xxx.png](assets/2023-12-29-xxx.png)](https://www.jotform.com/form/233544823564157)
```

**Comment by pitdagosti** [comment]
What do you think?

EE2366BA-6619-43FE-A118-B29E7AC37AE5

**Comment by gmacario** [comment]
I am not sure that the URL `https://www.jotform.com/form/233544823564157` inside the image is useful. But the link when clicking on the image IMHO is.

**Comment by pitdagosti** [comment]
ahhhh now I got it

**Review by gmacario — APPROVED** [review]
I added one commit which comments out the first image.

Now LGTM. Merging PR

**Pull request merged**
