### PR TITLE
[draft] ci: fix duplicate jobs

### LINKED ISSUE #47: [BUG]: ci: duplicate runs of the same jobs
### Description of the bug

Right now, the CI pipeline is triggered, either:

- By a commit on non-main branches
- By a PR

This results in duplicate jobs execution whenever pushing to a branch for which a PR is open.

My suggestion would be to deactivate the pipeline execution on push, or to create some logic to prevent duplicate jobs for when a commit is pushed on a branch that has a PR open.
I think the first solution makes more sense, as the current job only includes super linter.

If it will be required to add more jobs, then we can review the triggering rules.

### Steps To Reproduce

1. Create a new branch
2. Push some changes on the new branch
3. Open a PR from the new branch to main
4. Do an additional commit on the same branch

This^ will result in a total of 4 jobs (1 on point 2, 1 on point 3, and 2 on point 4), while the expected number is 3 (point 4 should only trigger 1).

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by davmacario**
Closes #47  

## 📑 Description

- Prevent duplicate jobs - now Super Linter is only ran on pull requests
- Create new job to build and push Depthai Docker image to the GitHub Container Registry

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

The PR is still in draft, as I am trying to find a way to test the new job (I am accepting suggestions).

I also would like to trigger the action when, either:

- The files `Dockerfile`, `requirements.txt` and `vision_webserver.py` are changed when pushing (or merging) to main
- The file defining the job is changed _regardless of the branch_

but it does not seem to be possible (as I can only define the `push` trigger once). If there was a way to do so, it would also be possible to test this job without having to merge to main first.

### CODE REVIEW

**Comment by davmacario** [comment]
@gmacario I am open to suggestions :)

**Comment by gmacario** [comment]
> @gmacario I am open to suggestions :)

Maybe reading the examples at https://github.com/super-linter/super-linter could help

**Comment by gmacario** [comment]
Concerning

> I also would like to trigger the action when, either:
> ...

I am quite sure you are familiar with https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow, aren't you?

**Comment by davmacario** [comment]
> I am quite sure you are familiar with https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow, aren't you?

I am now, and the documentation for the [`event_dispatch`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch) flag clearly says:

> **Note**: This event will only trigger a workflow run if the workflow file is on the default branch.

Indeed, despite having pushed changes that add the `workflow_dispatch` condition, I am not able to manually trigger the action as it is not on the default branch.

**Comment by gmacario** [comment]
@davmacario Re:

> Create new job to build and push Depthai Docker image to the GitHub Container Registry (to be tested)

Although this feature is quite welcome, I would suggest to handle this in a separate PR since it is not related to bug https://github.com/B-AROL-O/FREISA/issues/47 which this bug is supposed to fix

**Comment by davmacario** [comment]
@gmacario should work now

**Review by gmacario — APPROVED** [review]
With the caveat which I mentioned in https://github.com/B-AROL-O/FREISA/pull/48#issuecomment-2411895366 

> @davmacario Re:
> 
> > * Create new job to build and push Depthai Docker image to the GitHub Container Registry (to be tested)
> 
> Although this feature is quite welcome, I would suggest to handle that in a separate PR since it is not related to bug #47 which this PR is supposed to fix

LGTM. Merging PR

**Pull request merged**
